### PR TITLE
When we can't map a URL bail with 501 (not implemented rather than 404) to help distinguish this type of failure in the logs

### PR DESCRIPTION
**Pull request by matthew-andrews**
Potentially controversial

cc @commuterjoy @wheresrhys

### CODE REVIEW

**Comment by commuterjoy** [comment]
hmmm, could we not just push an error to sentry? it is technically a 404 and this will just mask more serious 5xx's.

**Comment by matthew-andrews** [comment]
logging to splunk already

**Comment by matthew-andrews** [comment]
i think might be ok. the errors are at a kind of manageable level now anyway

**Comment by commuterjoy** [comment]
:+1:

**Pull request closed without merging**
